name = "CurvilinearGrids"
uuid = "58b19789-dd19-4aa2-839c-c763a7b10301"
authors = ["Sam Miller <smil@lle.rochester.edu> and contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
